### ISSUE TITLE
GitHubActionsを有効化してNetlifyへのデプロイを自動化する

### ISSUE THREAD

**Issue by varu3** [codeforoita/covid19#3]
## 改善詳細 / Details of Improvement
- https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg の設定編に従ってGitHubActionsでNetlifyへのデプロイを自動化する

## 期待する見せ方・挙動 / Expected behavior
- GitHubActionsの設定自体は`.github/workflow`に入っているのでそちらを参照してください
  - https://github.com/codeforoita/covid19/tree/development/.github/workflows

- 特定のブランチにマージされた場合にCIが起動するようになっている。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by satetsu** [comment]
GitHubActionsを有効化しました。
